name: SUACT
favicon: null
layout_spectrum: 0.65911
typography_spectrum: 0.88589
title: Draft site for SUACT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e31936'
    - '#ffffff'
    - '#faddd6'
    - '#ef8885'
    - '#ffcc49'
  brandStrength: 0.9183820423204452
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
